### ISSUE TITLE
use google/subcommands for managing command components

### ISSUE THREAD

**Issue by shoenig** [modprox/taggit#18]
Currently `taggit` uses one big interface to sort of declare what top-level command line options are available. This doesn't actually help anything and is kinda gross. Instead, use [google/subcommands](https://github.com/google/subcommands) to help define commands.

**Comment by shoenig** [comment]
@ailurarctos @clly @deadok22 if ya'll are still using this, can you test `v1.0.0-rc.1` (mostly the publishing part)? If it seems fine feel free to tag `v1.0.0` yourselves ~ 

It's a huge [refactoring](https://github.com/modprox/taggit/pull/34/files) but functionally everything should be the same

**Comment by ailurarctos** [comment]
Sorry for the delay @shoenig. I tried this out and it seems to behave the same.
